# Generated by Django 5.2 on 2025-05-05 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldSeller',
            fields=[
                ('seller_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_management.seller')),
                ('subscription_type', models.CharField(choices=[('basic', 'Basic'), ('gold', 'Gold')], default='basic', max_length=20)),
                ('subscription_plan', models.CharField(choices=[('basic', 'Basic'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='basic', max_length=20)),
                ('subscription_end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('user_management.seller',),
        ),
    ]
