# Generated by Django 5.2 on 2025-05-05 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goldseller',
            table='goldseller',
        ),
    ]
