# Generated by Django 5.2 on 2025-04-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile_photos/default-profile.png', null=True, upload_to='profile_photos/'),
        ),
    ]
