# Generated by Django 5.2 on 2025-05-05 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_management', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='propertylike',
            table='propertylike',
        ),
    ]
